/* eslint-disable prettier/prettier */
const style: any = {
  login: {
    viewstyle: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    buttonstyle: {
      backgroundColor: '#7D67F7',
      padding: 15,
      borderRadius: 15,
      alignItems: 'center',
      borderBottom: 10,
    },
    textstyle: {color: 'black', fontFamily: 'San-serif', fontSize: 22},
    loginviewstyle: {
      padding: 10,
      display: 'flex',
      justifyContent: 'space-between',
      flexDirection: 'column',
      flex: 1,
      backgroundColor: '#654EE8',
    },
    innerview: {
      padding: 10,
      display: 'flex',
      justifyContent: 'space-between',
      flexDirection: 'column',
      marginTop: 250,
    },
    innerviewbutton: {
      backgroundColor: '#B4BAFF',
      padding: 15,
      borderRadius: 15,
      alignItems: 'center',
      marginBottom: 10,
      width: '45%',
    },
    butt: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginVertical: 20,
    },
  },
  error: {
    container: {
      flex: 1,
      display: 'flex',
      backgroundColor: '#B4BAFF',
      alignItems: 'center',
      justifyContent: 'center',
    },
    one: {padding: 10},
    headertext: {color: 'red', fontSize: 30, fontWeight: 'bold'},
    content: {
      flex: 1,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      padding: 15,
    },
    innercontent: {
      borderWidth: 2,
      borderColor: '#654EE8',
      padding: 10,
      borderRadius: 20,
      backgroundColor: '#654EE8',
    },
    contenttext: {fontSize: 25, color: '#B4BAFF'},
    contentbuttonview: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 10,
      width: 170,
    },
    contentbuttonlogin: {
      backgroundColor: '#654EE8',
      padding: 15,
      borderRadius: 15,
      alignItems: 'center',
      marginBottom: 10,
    },
    contentbuttonregister: {
      backgroundColor: 'grey',
      padding: 15,
      borderRadius: 15,
      alignItems: 'center',
      marginBottom: 10,
    },
  },
  textinput: {
    container: {
      display: 'flex',
      flexDirection: 'column',
      backgroundColor: '#7D67F7',
      borderRadius: 15,
      padding: 10,
      marginBottom: 10,
    },
    textview: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
    },
    inputstyle: {
      borderWidth: 0,
      borderColor: 'gray',
      flex: 1,
      color: 'black',
    },
    validatestyleerror: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'darkred',
      borderRadius: 25,
    },
    validatestylemark: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'lightgreen',
      borderRadius: 25,
    },
    validatetext: {color: 'darkred', fontWeight: '400'},
  },
  register: {
    stylez: {
      marginBottom: 10,
      padding: 15,
      borderWidth: 0,
      paddingHorizontal: 10,
      borderRadius: 15,
      backgroundColor: '#7D67F7',
      color: 'white',
    },
    container: {
      padding: 5,
      display: 'flex',
      flex: 1,
      backgroundColor: '#654EE8',
    },
    innerContainer: {
      padding: 15,
      display: 'flex',
      flex: 1,
    },
    firebaseButton: {
      borderRadius: 5,
      width: 150,
      height: 50,
      backgroundColor: '#B4BAFF',
      alignItems: 'center',
      justifyContent: 'center',
    },
    button: {
      backgroundColor: '#B4BAFF',
      padding: 15,
      borderRadius: 15,
      alignItems: 'center',
      marginBottom: 10,
      textTransform: 'uppercase',
    },
    images: {
      padding: 5,
      width: 300,
      height: 160,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    innerImage: {
      padding: 5,
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'white',
      borderRadius: 50,
    },
    imageStyle: {width: 150, height: 150, borderRadius: 50},
    inputStyle: {flex: 1, marginTop: 10},
    loadingStyle: {marginTop: 5},
    footerStyle: {
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    footerText: {color: 'black', fontFamily: 'San-serif', fontSize: 22},
    footerButton: {
      backgroundColor: '#7D67F7',
      padding: 15,
      borderRadius: 15,
      alignItems: 'center',
      borderBottom: 10,
    },
  },
  dashboard: {
    dashboardView: {
      height: 200,
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'space-between',
      backgroundColor: '#B4BAFF',
      borderBottomLeftRadius: 35,
      borderBottomRightRadius: 35,
      padding: 3,
      marginBottom: 5,
    },
    innnerDashboardView: {
      height: 200,
      display: 'flex',
      padding: 3,
      backgroundColor: '#B4BAFF',
      borderBottomLeftRadius: 35,
      borderBottomRightRadius: 35,
      borderWidth: 1,
    },
    innerDashboardViewTop: {
      padding: 3,
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      flexDirection: 'row',
    },
    innerDashboardViewBottom: {
      display: 'flex',
      alignItems: 'center',
      margin: 3,
    },
    innerTop: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      flexDirection: 'row',
    },
    innerTextTop: {
      fontSize: 30,
      fontWeight: 'bold',
      color: '#654EE8',
    },
    innerBottom: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      flexDirection: 'row',
    },
    innerBottomText: {fontWeight: 'bold', fontSize: 20, color: 'black'},
    innerBottomIcon: {
      width: 30,
      height: 30,
      backgroundColor: '#654EE8',
      borderRadius: 10,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: 5,
    },
    innerDashboardInner: {
      display: 'flex',
      alignItems: 'center',
      margin: 3,
      padding: 7,
      borderRadius: 25,
      backgroundColor: '#654EE8',
    },
    innerDashboardInnerImage: {
      width: 120,
      height: 120,
      borderRadius: 25,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    outer: {
      flex: 1,
      backgroundColor: '#654EE8',
      borderTopRightRadius: 35,
      borderTopLeftRadius: 35,
    },
    outerStyle: {
      padding: 15,
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    listStyle: {
      flex: 1,
      backgroundColor: '#E6EDF7',
      borderTopRightRadius: 35,
      borderTopLeftRadius: 35,
    },
  },
  twitter: {
    container: {
      width: 100,
      height: 80,
      backgroundColor: '#7D67F7',
      borderRadius: 10,
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    text: {color: 'white', fontWeight: 'bold', fontStyle: 'italic'},
  },
  chat: {
    container: {flex: 1},
    view: {flex: 1, margin: 1},
    innerView: {
      flexDirection: 'row',
      padding: 5,
      justifyContent: 'space-between',
      alignItems: 'center',
      height: 80,
      borderBottomLeftRadius: 35,
      borderBottomRightRadius: 35,
    },
    icon: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 1,
      borderRadius: 15,
    },
    image: {
      width: 40,
      height: 40,
      borderRadius: 20,
      borderWidth: 2,
    },
    users: {
      flex: 1,
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      paddingTop: 10,
      paddingBottom: 10,
    },
    button: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      padding: 5,
      marginRight: 2,
    },
    flatlist: {
      flex: 1,
      paddingTop: 5,
      display: 'flex',
    },
    inputView: {
      flexDirection: 'row',
      padding: 3,
      justifyContent: 'center',
      alignItems: 'center',
      maxHeight: 150,
      borderTopLeftRadius: 35,
      borderBottomRightRadius: 35,
    },
    input: {
      flex: 1,
      margin: 2,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    render: {
      backgroundColor: 'transparent',
    },
    touchable: {
      maxWidth: 320,
      padding: 7,
      display: 'flex',
      marginBottom: 10,
      borderRadius: 15,
      flexDirection: 'row',
    },
    textStyle: {fontSize: 16},
    viewIcon: {
      display: 'flex',
      // justifyContent: 'space-between',
      alignItems: 'center',
    },
    design: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      marginLeft: 20,
    },
    text: {display: 'flex', maxWidth: '80%'},
    tes: {marginRight: 3},
  },
  user: {
    imageStyle: {
      width: 50,
      height: 50,
      borderRadius: 25,
      borderWidth: 2,
      borderColor: '#008000',
    },
    view: {marginRight: 5},
  },
  landing: {
    buttonView: {
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginVertical: 40,
      marginHorizontal: 20,
    },
    button: {
      padding: 15,
      flex: 1,
      height: 70,
      display: 'flex',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#C2E9AB',
      borderTopRightRadius: 35,
      borderBottomLeftRadius: 35,
    },
    container: {
      flex: 1,
      display: 'flex',
      justifyContent: 'space-between',
      padding: 10,
      alignItems: 'center',
    },
    flex: {flex: 1},
    textBig: {fontSize: 35, fontWeight: '900', color: 'cyan'},
    textMid: {fontSize: 20, fontWeight: '700', color: 'lightcyan'},
    textSmall: {fontSize: 25, fontWeight: '500', color: 'lightcyan'},
    animation: {
      display: 'flex',
      justifyContent: 'center',
      padding: 10,
      alignItems: 'center',
      marginBottom: 373,
    },
  },
};

export default style;
